-- AlterTable
ALTER TABLE `driver` ADD COLUMN `sokcet_id` VARCHAR(191) NULL,
    MODIFY `otp` VARCHAR(191) NULL,
    MODIFY `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);

-- AlterTable
ALTER TABLE `orders` MODIFY `created_at` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3);
