image: node:20.15.0
services:
  - mysql:9.0.0
stages:
  - setup
  - install
  - test
  - build
  - deploy

variables:
  MYSQL_DATABASE: uberin
  MYSQL_PASSWORD: 123456
  MYSQL_ROOT_PASSWORD: 123456
  DATABASE_URL: mysql://root:123456@localhost:3306/uberin


  
cache:
  paths:
    - node_modules/



setup:
  stage: setup
  script:
  - apt-get update && apt-get install -y git curl libmcrypt-dev default-mysql-
  - mysql --version
  - sleep 20
  - echo "SHOW tables;"| mysql -u root -p"$MYSQL_ROOT_PASSWORD" -h "${MYSQL_HOST}" "${MYSQL_DATABASE}"

install:
  stage: install
  script:
    - npm install
    - npx prisma migrate deploy

test:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
      
deploy:
  stage: deploy
  script:
    - echo "Deploying to production server"