image: node:20.15.0
services:
  - mysql:9.0.0
stages:
  - install
  - test
  - build
  - deploy


variables:
  MYSQL_DATABASE: uberin
  MYSQL_ROOT_PASSWORD: my_password
  MYSQL_USER: my_user
  MYSQL_PASSWORD: my_user_password
  DATABASE_URL: mysql://my_user:my_user_password@mysql:3306/my_database

cache:
  paths:
    - node_modules/

before_script:
     # ENV is exported as a path to your "ENV" file, 
        # this is copying it to a local '.env' file
  - cp $ENV .env
        # If you need it, this is a way to export the
        # environment variables inside your file
  - source .env; export $(cut -d= -f1 .env);
        # Debugging the pipelines
  - ls -lah
  - npm install


setup:
  stage: setup
  script:
    # Install Prisma CLI
    - npx prisma --version
    # Wait for MySQL service to be available
    - until mysql -h mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "SHOW DATABASES;" > /dev/null 2>&1; do sleep 10; done
    # Create the database if it doesn't exist
    - mysql -h mysql -u"$MYSQL_USER" -p"$MYSQL_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;"
    # Run Prisma migrations
    - npx prisma migrate deploy


install:
  stage: install
  script:
    - npm install

test:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
      
deploy:
  stage: deploy
  script:
    - echo "Deploying to production server"