image: node:20.15.0

stages:
  - install
  - test
  - build
  - deploy

variables:
  HEROKU_APP_NAME: uberin

before_script:
  - npm install

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  needs:
    - install_dependencies
  script:
    - npm run test

build:
  stage: build
  image: node:16
  script:
    - npm run build
  dependencies:
    - install_dependencies
  artifacts:
    paths:
      - dist/


deploy:
  stage: deploy
  script:
    - apt-get update -y
    - apt-get install curl -y
    - curl https://cli-assets.heroku.com/install.sh | sh
    - echo $HEROKU_API_KEY | heroku auth:token
    - heroku git:remote -a $HEROKU_APP_NAME
    - git config user.email "Nurfaizin318@gmail.com"
    - git config user.name "Nur Faizin"
    - git add dist -f
    - git commit -m "Deploy to Heroku"
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git `git subtree split --prefix dist master`:refs/heads/master --force
  only:
    - main
  dependencies:
    - build