image: node:20.15.0

stages:
  - install
  - test


cache:
  paths:
    - node_modules/

install:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  dependencies:
    - install_dependencies
  image: mysql
  services:
    - name: mysql:latest
      alias: mysql
  variables:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_DATABASE: uberin
  before_script:
   - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"
  script:
    - npm test