image: node:20.15.0
services:
  - mysql:9.0.0
stages:
  - install
  - setup
  - test
  - build
  - deploy


variables:
  MYSQL_DATABASE: uberin
  MYSQL_USER: root
  MYSQL_PASSWORD: 123456
  DATABASE_URL: mysql://root:123456@localhost:3306/uberin

cache:
  paths:
    - node_modules/

before_script:
  - mysql --version
  - echo "Setting up MySQL database..."
  - mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};"
  - mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'localhost' IDENTIFIED BY '${MYSQL_PASSWORD}';"
  - mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'localhost';"
  - mysql -u root -p${MYSQL_ROOT_PASSWORD} -e "FLUSH PRIVILEGES;"
     # ENV is exported as a path to your "ENV" file, 
        # this is copying it to a local '.env' file
  - cp $ENV .env
        # If you need it, this is a way to export the
        # environment variables inside your file
  - source .env; export $(cut -d= -f1 .env);
        # Debugging the pipelines
  - ls -lah
  - npm install
  - npx prisma migrate deploy


setup:
  stage: setup
  script:
    - apt-get update && apt-get --assume-yes install mysql-server mysql-common mysql-client
    - service mysql start
    - echo "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('password');" | mysql -u root
    - echo "SELECT 'OK';" | mysql -uroot -p"$MYSQL_ROOT_PASSWORD" -h mysql "$MYSQL_DATABASE"


install:
  stage: install
  script:
    - npm install

test:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
      
deploy:
  stage: deploy
  script:
    - echo "Deploying to production server"