image: node:20.15.0

stages:
  - install
  - test
  - build
  - deploy

variables:
  HEROKU_APP_NAME: uberin

before_script:
  - npm install

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  needs:
    - install_dependencies
  script:
    - npm run test

build:
  stage: build
  needs:
    - install_dependencies
  script:
    - npm run build

deploy:
  stage: deploy
  script:
    - apt-get update -y
    - apt-get install curl -y
    - curl https://cli-assets.heroku.com/install.sh | sh
    - heroku auth:token
    - echo "$HEROKU_API_KEY" | heroku auth:token
    - git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git
    - git push heroku HEAD:master
  only:
    - main