image: node:20.15.0

services:
  - mysql:9.0.0

variables:
  MYSQL_DATABASE: uberin
  MYSQL_ROOT_PASSWORD: 123456

stages:
  - test
  - deploy

connect_and_install:
  stage: test
  image: mysql
  script:
    - echo "SELECT 'OK';" | mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE"
    - mysql -h mysql -u root -p"$MYSQL_ROOT_PASSWORD" -e "SHOW DATABASES;"
    - npm install
    - npx prisma migrate deploy --skip-seed  # Ubah sesuai dengan perintah prisma Anda

deploy_job:
  stage: deploy
  script:
    - echo "Deploying your application..."  # Tambahkan perintah atau skrip deploy sesuai kebutuhan
  tags:
    - docker
  environment:
    name: production