image: node:20.15.0
services:
  - mysql:9.0.0
stages:
  - install
  - test
  - build
  - deploy

cache:
  paths:
    - node_modules/

before_script:
  - npm install

install:
  stage: install
  script:
    - npm install

test:
  stage: test
  script:
    - npm test

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
      
deploy:
  stage: deploy
  script:
    - echo "Deploying to production server"