# .gitlab-ci.yml

# Definisikan stages yang akan digunakan
stages:
  - install
  - test
  - build
  - deploy

# Definisikan layanan yang akan digunakan (Node.js dan MySQL)
services:
  - name: node:20.15.0
    alias: node
  - name: mysql:9.0.0
    alias: mysql
    entrypoint: ["docker-entrypoint.sh", "mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: uberin
      MYSQL_PASSWORD: 123456

# Definisikan job untuk setiap stage
install_dependencies:
  stage: install
  script:
    - npm install
    - npx prisma migrate deploy
  tags:
    - docker

run_tests:
  stage: test
  script:
    - npm run  test  # Sesuaikan dengan perintah untuk menjalankan tes Anda
    - npm run lint  # Contoh: menjalankan linter
  tags:
    - docker

build_application:
  stage: build
  script:
    - npm run build  # Contoh: menjalankan build aplikasi
  artifacts:
    paths:
      - dist/  # Contoh: path untuk hasil build
  tags:
    - docker

deploy_to_production:
  stage: deploy
  script:
    - echo "Deploying to production..."  # Contoh: perintah untuk deploy
    # Tambahkan perintah atau skrip deploy sesuai kebutuhan Anda
  environment:
    name: production
    url: https://your-production-url.com  # Contoh: URL produksi
  tags:
    - docker
  when: manual  # Atur untuk manual jika diperlukan konfirmasi deploy

# Tambahkan konfigurasi tambahan sesuai kebutuhan proyek Anda
