version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:12.22.7-bullseye-browsers-legacy # Sesuaikan dengan versi Node.js yang Anda gunakan
    working_directory: ~/repo

jobs:
  install-dependencies:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

  test:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Run Tests
          command: npm run  test

  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Build Project
          command: npm run build

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-dependencies
      - test:
          requires:
            - install-dependencies
      - build:
          requires:
            - test
